version: '3.8'

services:
  invictaweb:
    build: 
      context: .
      dockerfile: Dockerfile.monolith
    container_name: invictaweb
    ports:
      - "9090:80"
      - "9443:443"
    volumes:
      # Database persistence
      - ./db:/var/www/db
      - ./data:/var/www/data
      
      # Application code
      - ./services/aoc-timer-map:/var/www/html
      - ./services/main-portal/dist:/var/www/html/portal
      
      # Configuration
      - ./infrastructure/nginx/monolith.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      
      # SSL certificates (if available)
      - ./infrastructure/ssl:/etc/ssl/certs/invictaweb:ro
      
      # Logs
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php
    environment:
      - ENVIRONMENT=production
      - DB_PATH=/var/www/db/mydb.sqlite
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=300
    networks:
      - invictaweb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development services (optional)
  portal-dev:
    profiles: ["dev"]
    working_dir: /app
    volumes:
      - ./services/main-portal:/app
    ports:
      - "4200:4200"
    command: npm run start
    networks:
      - invictaweb

  map-dev:
    profiles: ["dev"] 
    working_dir: /app
    volumes:
      - ./services/aoc-timer-map/dev:/app
    ports:
      - "4201:4200"
    command: npm run start
    networks:
      - invictaweb

networks:
  invictaweb:
    driver: bridge
    
volumes:
  invictaweb_db:
    driver: local
  invictaweb_logs:
    driver: local
