version: '3.8'

services:
  # BookStack Wiki Service (Production)
  bookstack-prod:
    image: linuxserver/bookstack:latest
    container_name: bookstack-prod
    ports:
      - "8083:80"  # BookStack on port 8083 (production)
    volumes:
      - ./bookstack-data:/config
      - ./bookstack-backups:/backups
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://84.247.141.193:8083
      - APP_KEY=base64:df2SHp9jQo9C9GVjGZhA1BfeyGiyG0pn2IlRBzuu8W4=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/config/database.sqlite
    networks:
      - aoctimermap-network
    restart: unless-stopped

networks:
  aoctimermap-network:
    driver: bridge